### ISSUE TITLE
Error when registering a new user

### ISSUE THREAD

**Issue by SanjeevRJ** [ActiveBrainAtlas2/activebrainatlasadmin#211] opened 2023-09-13 14:50 UTC
A researcher at Princeton is interested in uploading his data to BrainSharer but when he tried to register for an account locally and using his GitHub account the following error was thrown: "Server Error (500)".

**Comment by eddyod** [comment] 2023-09-13 18:27
I fixed the local signup issue, but I can't reproduce the Github one. Can someone else try logging in with Github? And note, when you login with Github, that doesn't mean you have automatic access to https://www.brainsharer.org/brainsharer/admin . Just https://www.brainsharer.org

**Comment by drinehart1** [comment] 2023-09-13 19:45
I had Jacob try to login with his github account but he receives a 500 server error message upon entering github credentials.

 

URL forwards to:

https://www.brainsharer.org/brainsharer/github/?code=153cb9e6c5336e29accd <https://urldefense.com/v3/__https:/www.brainsharer.org/brainsharer/github/?code=153cb9e6c5336e29accd__;!!Mih3wA!EywEGp0wDmD5b27_vgU4MzxAfkEc8DN0yNB6xdR5UhS9W0AbJPg0XeBKE-O79tZ8IeDPCGxd_PtKC0LknJcp4JPsBw$> 

Server Error (500)

 

 

Duane

**Comment by eddyod** [comment] 2023-09-14 01:18
I'm going to remove the Github login option. It is too buggy.

**Comment by eddyod** [comment] 2023-09-14 07:07
This has been fixed. Users can local login, register for new local account and reset lost password. Github login was removed.

**Comment by eddyod** [comment] 2023-10-25 14:44
I'm closing this.

**Closed as completed by eddyod** 2023-10-25 14:44 UTC
